### ISSUE TITLE
Improve API, providing filter AST in VirtualWindows

### ISSUE THREAD

**Issue by vndzzz** [espertechinc/esper#130]
Currently through api it is possible only to handle and conditions, i.e. `from a where a.key < b.highValue and a.key > b.lowValue`. 
When `and` predicate is changed with `or` predicate it is impossible to get filter conditions. Maybe it would be better to change Api in `VirtualWindowLookup` to make it possible handle full AST of where conditions.

**Comment by bernhardttom** [comment]
This information is already available from the statement object model `EPCompiler#eplToModel`.
The `VirtualWindowLookup ` is a runtime concept and there is no AST available at runtime since only the compiler has an AST and the compiler throws away the AST once its done spitting out the `EPCompiled` which only has binary.
