### ISSUE TITLE
Improve Compile and Deploy efficiency in Esper 8+

### ISSUE THREAD

**Issue by subrata304** [espertechinc/esper#250]
Creating new issue with the continuation of https://github.com/espertechinc/esper/issues/249

We used the compileDeploy() method mentioned in the Esper documentation to compile and deploy statements. But I see you mentioned something like env.compile("EPL Statements"), Could you please provide the whole code for this? Looks like you are doing it in different way.

```
EPCompiled compiled = env.compile("select * from SupportBean");
        long start = System.currentTimeMillis();
        for (int i = 0; i < 1000; i++) {
            env.deploy(compiled);
        }
        long end = System.currentTimeMillis();
        System.out.println(end - start);
```

Secondly our EPL statements are complex in nature where we have multiple filter criteria with all sorts of operator like '=', '!=', '>', '<', '>=','<=', 'OR', 'AND', 'in', 'not in' and even complex regex expression as well.
Moreover all these kind of EPL statements are getting loaded in memory within few seconds with Esper V5 but with Esper V8 it's taking huge time as I have mentioned.

Lastly, we have very frequent update to this EPL statements and also we need to remove/add these statements from memory frequently to support some business logic.

All of these are working fine in Esper V5 and even in EsperV8 rate of matching EPL statements is actually gone high but we are facing problem with loading time of the statements.

E.g. -

'select * from Event( ( eventType = toUUID(“bc6018d6-6376-4f22-ad39-3ad5bce49c9e”) ) and ( ( property(‘’messagingConfigurationName’’).value = “config1" ) and ( property(‘’queueName’’).value = “TEST.QUEUE” ) and ( ( toNumber(property(‘’currentDepth’’).value) >= 1000 ) or ( toNumber(property(‘’messageAge’’).value) >= 10 ) ) ) )'
Above statement took 1186 ms to compile and 102 ms to deploy

’select * from Event( ( eventType = toUUID(“c7df6e15-b411-4e36-8b69-900321ee4c91") ) and ( ( property(‘’Tag’’).value regexp “.Kubernetes]app:status.” ) and ( property(‘’Tag’’).value regexp “.Namespace:wnleld.” ) and ( property(‘’Tag’’).value regexp “.EnvType:dev.” ) and ( property(‘’Tag’’).value regexp “.InfrastructureType:k8s.” ) ) )'
Above statement took 1214 ms to compile and 89 ms to deploy

Could you please point us whether we are doing this in right way or not, keeping in mind we have 200k+ statements to load in memory at server start?

**Comment by bernhardttom** [comment]
"env.compile" is just compile.

**Comment by gavol** [comment]
I think what has been suggested is to compile the EPL statements once (until they do not change, of course), make them persistent in a jar file (as an example of container) and then just deploy them in your application. The EPL can be easily compiled in advance and re-used,

I am in a similar situation where EPL statements need to be loaded/unloaded several times during the life-time of the application. Since my compilation times are not huge, I compile and save the compiled EPL in jar files when the application starts and, when needed, I load the compiled modules from jar files (that is really fast) without the extra time needed for compilation.
