### ISSUE TITLE
7.0.0: Janino packages are not included into OSGi Import-Package

### ISSUE THREAD

**Issue by dpishchukhin** [espertechinc/esper#97]
`com.espertech.esper.client.ConfigurationException: Failed to load Janino compiler class 'org.codehaus.janino.SimpleCompiler': org.codehaus.janino.SimpleCompiler not found by com.espertech.esper [16]
	at com.espertech.esper.codegen.compile.CodegenCompilerJanino.setupJanino(CodegenCompilerJanino.java:142) [16:com.espertech.esper:7.0.0]
	at com.espertech.esper.codegen.compile.CodegenCompilerJanino.<init>(CodegenCompilerJanino.java:59) [16:com.espertech.esper:7.0.0]
	at com.espertech.esper.core.service.EPServicesContextFactoryDefault.makeEngineImportService(EPServicesContextFactoryDefault.java:536) [16:com.espertech.esper:7.0.0]
`

**Comment by bernhardttom** [comment]
Can be fixed by disabling byte code gen

**Comment by dpishchukhin** [comment]
agree but I would like to test byte code gen with OSGi.

**Comment by bernhardttom** [comment]
Feel free to add to the manifest. They are an optional dependency and if there will be added to the manifest they become a required dependency in OSGi.

**Comment by rlegorreta** [comment]
I tried to create the Manifest to the janino jar (two of them) but they have many dependencies to ester that could not be added.
Any success to create the manifest?

**Comment by bernhardttom** [comment]
What are the "dependencies to ester"???

**Comment by rlegorreta** [comment]
Thanks for your promptly answer.
When I created a Manifest file for janino.3.0.7.jar and run it inside Equinox (i.e. Liferay DXP) it is installed correctly, but at run-time the OSGi container sends errors for class not found because there is no import package inside the manifest (for example import for com.espertech.esper.epl.core.resultset.core, com.espertech.esper.collection, and many more).
The same happens for janino-common-compiler.3.07.jar but the dependencies are less.
For example: inside the janino SimpleCompiler class it is called some Esper classes.

Or maybe I'm doing something wrong. Do you need the trace log?

**Comment by rlegorreta** [comment]
I already import the janino package in Esper, it advances since now Esper recognize janino classes. But the error is inside the janino packages (e.g., SimpleCompiler class) that calls Esper classes (I don't know how, if it is by reflection or some interface implementation, I need to check the source code) and after adding many Esper package in janino I could not advance more. This is a circular class dependency that I don't understand yet.
I'm going to start all over again, because maybe I´m doing something wrong. Your advise should work.
If you solved the issue please let me know and send me the jars.

**Comment by dpishchukhin** [comment]
I managed to use Esper with Janino and OSGi

Janino bnd:
```
Export-Package: org.codehaus.janino.*;version=3.0.7
Import-Package: org.apache.tools.ant*;resolution:=optional, *
```

Esper bnd:
```
Export-Package: com.espertech.esper.*;version=7.0.0
Import-Package: com.sun.org.apache.xerces.internal.*;resolution:=optional, \
    sun.reflect.*;resolution:=optional, \
    org.codehaus.janino;version="[3,4)", \
    *
```

**Comment by rlegorreta** [comment]
Excellent

I wil try with these bnd files.

Ricardo.

**Comment by rlegorreta** [comment]
This is because janino que java reflection tries to use several esper classes (not just the TaransformEventIterator but many more) and janino bunds does not have any import package for esper  (so it is a circular dependency).
Any idea how can I solve this problem?

**Comment by rlegorreta** [comment]
How do I do that

**Comment by bernhardttom** [comment]
Thread.currentThread().setContextClassLoader(...);

**Comment by rlegorreta** [comment]
Thanks for your help!! Now it works:
When I add Thread.currentThread().setContextClassLoader(...); and see what Esper classes could not be loaded I added and import statement in the java class and they work... so I realized what was the error, it was not to set the class loader but:

In my Liferay portel bundle bnd file I defined de Import packages as '*' so it just add the packages that are referenced 'at compile time'. Since janino uses the Esper classes with classLoader (i.e., at run-time) it never adds the correct Import packages.

So the solution was to include as many Esper Import packages in my bnd portlet Liferay bundle and voila it works!!!! So finally I did not need to set the class loader, but if gave me the right debug idea to catch what was the error.

Thanks for your help !!
